replicaCount: 1

image:
  repository: ghcr.io/vasary/coins-inventory:sha-{container_version}
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: "coins-inventory"
fullnameOverride: "coins-inventory"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
     nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
    - host: coins-inventory.cfv3.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
   limits:
     cpu: 500m
     memory: 256Mi
   requests:
     cpu: 250m
     memory: 128Mi

livenessProbe:
  httpGet:
    path: /api/maintenance/health
    port: http
readinessProbe:
  httpGet:
    path: /api/maintenance/health
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes:
 - name: prod-config
   secret:
     secretName: coins-inventory-config
     optional: false

volumeMounts:
 - name: prod-config
   mountPath: "/app/.env.prod"
   subPath: ".env.prod"
   readOnly: true

nodeSelector: {}
tolerations: []
affinity: {}
