FROM php:8.4-fpm-alpine

ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /app

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
COPY . /app

RUN composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader --prefer-dist
