services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tests\Behat\Context\:
        resource: '../tests/Behat/Context'

    Infrastructure\Persistence\Redis\Repository\CoinRepository:
        public: true

    Infrastructure\Test\Fixture\CoinFixture:
        public: true

    Application\UseCase\Coin\Find\FindAllCoinsUseCase:
        public: true

    Application\UseCase\Coin\Place\PlaceCoinUseCase:
        public: true

    Domain\Coin\Factory\CoinFactory:
        public: true

    matcher:
        class: Coduo\PHPMatcher\PHPMatcher

    Tests\Behat\Context\PlaceCoinContext:
        arguments: ['@matcher']

    guzzle.gold-api.client:
        class: GuzzleHttp\Client
        arguments:
            $config:
                handler: '@test.guzzle.handler'

    test.handler.mock:
        class: GuzzleHttp\Handler\MockHandler

    test.handler:
        class: Infrastructure\GoldAPI\Test\Mock\Handler
        arguments:
            $handler: '@test.handler.mock'

    test.guzzle.handler:
        class: GuzzleHttp\HandlerStack
        factory: [ 'GuzzleHttp\HandlerStack', 'create' ]
        arguments: [ '@test.handler' ]

